[package]
authors = ["William Wang"]
edition = "2021"
name = "skip_it"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
