version = "Two"

binop_separator = "Front"
blank_lines_lower_bound = 0
blank_lines_upper_bound = 1
brace_style = "SameLineWhere"
comment_width = 80
control_brace_style = "AlwaysSameLine"
edition = "2021"
empty_item_single_line = true
error_on_line_overflow = true
error_on_unformatted = true
force_explicit_abi = true
format_code_in_doc_comments = true
format_strings = true
group_imports = "StdExternalCrate"
imports_granularity = "Module"
max_width = 120
merge_derives = true
reorder_imports = true
wrap_comments = true
